"""Form preset templates — shared between routers and seeding services."""

_FORM_PRESETS: dict[str, dict] = {
    "dental_intake": {
        "name": "New Patient Health History",
        "description": "Collect essential health information from new dental patients before their first visit.",
        "fields": [
            {"id": "full_name", "type": "text", "label": "Full Name", "required": True, "placeholder": "First and Last Name"},
            {"id": "dob", "type": "date", "label": "Date of Birth", "required": True},
            {"id": "email", "type": "email", "label": "Email", "required": True, "placeholder": "your@email.com"},
            {"id": "phone", "type": "phone", "label": "Phone Number", "required": True, "placeholder": "(555) 123-4567"},
            {"id": "insurance_carrier", "type": "text", "label": "Insurance Carrier", "required": False, "placeholder": "e.g. Delta Dental, Cigna"},
            {"id": "insurance_member_id", "type": "text", "label": "Insurance Member ID", "required": False},
            {"id": "allergies", "type": "textarea", "label": "Allergies (medications, latex, etc.)", "required": False, "placeholder": "List any known allergies"},
            {"id": "medications", "type": "textarea", "label": "Current Medications", "required": False, "placeholder": "List all current medications"},
            {"id": "conditions", "type": "select", "label": "Do you have any of the following?", "required": False, "options": ["None", "Diabetes", "Heart Disease", "High Blood Pressure", "Bleeding Disorder", "Asthma", "Other"]},
            {"id": "pregnant", "type": "radio", "label": "Are you currently pregnant?", "required": False, "options": ["No", "Yes", "Not Applicable"]},
            {"id": "last_dental_visit", "type": "select", "label": "When was your last dental visit?", "required": False, "options": ["Less than 6 months", "6-12 months", "1-2 years", "More than 2 years", "Never"]},
            {"id": "concerns", "type": "textarea", "label": "What brings you in today?", "required": False, "placeholder": "Describe any dental concerns or symptoms"},
            {"id": "consent", "type": "checkbox", "label": "I consent to treatment and acknowledge that the information provided is accurate", "required": True},
        ],
        "success_message": "Thank you! Your health history has been received. We look forward to seeing you at your appointment.",
    },
    "medical_intake": {
        "name": "Patient Registration Form",
        "description": "New patient registration and medical history for healthcare practices.",
        "fields": [
            {"id": "full_name", "type": "text", "label": "Full Name", "required": True},
            {"id": "dob", "type": "date", "label": "Date of Birth", "required": True},
            {"id": "email", "type": "email", "label": "Email", "required": True},
            {"id": "phone", "type": "phone", "label": "Phone Number", "required": True},
            {"id": "insurance_carrier", "type": "text", "label": "Insurance Provider", "required": False},
            {"id": "insurance_id", "type": "text", "label": "Insurance ID / Policy Number", "required": False},
            {"id": "allergies", "type": "textarea", "label": "Known Allergies", "required": False},
            {"id": "medications", "type": "textarea", "label": "Current Medications", "required": False},
            {"id": "medical_history", "type": "textarea", "label": "Relevant Medical History", "required": False},
            {"id": "reason_for_visit", "type": "textarea", "label": "Reason for Visit", "required": True},
            {"id": "consent", "type": "checkbox", "label": "I consent to treatment and acknowledge the privacy notice", "required": True},
        ],
        "success_message": "Thank you for completing your registration. We'll see you at your appointment.",
    },
    "contractor_estimate": {
        "name": "Request a Free Estimate",
        "description": "Collect project details for a free estimate.",
        "fields": [
            {"id": "name", "type": "text", "label": "Your Name", "required": True},
            {"id": "email", "type": "email", "label": "Email", "required": True},
            {"id": "phone", "type": "phone", "label": "Phone", "required": True},
            {"id": "address", "type": "text", "label": "Property Address", "required": True},
            {"id": "property_type", "type": "select", "label": "Property Type", "required": False, "options": ["Single-family home", "Townhome / Condo", "Multi-family", "Commercial", "Other"]},
            {"id": "service_type", "type": "select", "label": "Type of Service", "required": True, "options": ["Repair", "Replacement", "Installation", "Inspection", "Emergency", "Other"]},
            {"id": "project_type", "type": "select", "label": "Project Scope", "required": False, "options": ["Small repair", "Medium project", "Large remodel", "New build", "Not sure"]},
            {"id": "description", "type": "textarea", "label": "Describe the Project", "required": True, "placeholder": "What do you need done?"},
            {"id": "timeline", "type": "select", "label": "When do you need this done?", "required": False, "options": ["ASAP", "This week", "This month", "Flexible"]},
            {"id": "budget", "type": "select", "label": "Budget Range", "required": False, "options": ["Under $500", "$500-$2,500", "$2,500-$10,000", "$10,000+", "Not sure"]},
            {"id": "preferred_contact", "type": "select", "label": "Preferred Contact Method", "required": False, "options": ["Phone", "Text", "Email"]},
            {"id": "photos", "type": "text", "label": "Link to Photos (optional)", "required": False, "placeholder": "Google Drive or Dropbox link"},
        ],
        "success_message": "Thanks! We'll review your request and get back to you with an estimate within 24 hours.",
    },
    "legal_intake": {
        "name": "New Client Intake Form",
        "description": "Collect case details and client information for initial consultation.",
        "fields": [
            {"id": "full_name", "type": "text", "label": "Full Name", "required": True},
            {"id": "email", "type": "email", "label": "Email", "required": True},
            {"id": "phone", "type": "phone", "label": "Phone Number", "required": True},
            {"id": "case_type", "type": "select", "label": "Type of Legal Matter", "required": True, "options": ["Family Law", "Estate Planning", "Personal Injury", "Criminal Defense", "Business/Corporate", "Real Estate", "Immigration", "Employment", "Other"]},
            {"id": "description", "type": "textarea", "label": "Brief Description of Your Situation", "required": True, "placeholder": "Please describe your legal matter in a few sentences"},
            {"id": "opposing_party", "type": "text", "label": "Opposing Party Name (if applicable)", "required": False},
            {"id": "deadline", "type": "date", "label": "Any Upcoming Court Dates or Deadlines?", "required": False},
            {"id": "prior_attorney", "type": "radio", "label": "Have you worked with another attorney on this matter?", "required": False, "options": ["No", "Yes"]},
            {"id": "preferred_contact", "type": "select", "label": "Preferred Contact Method", "required": False, "options": ["Phone", "Email", "Text"]},
            {"id": "consent", "type": "checkbox", "label": "I understand that submitting this form does not create an attorney-client relationship", "required": True},
        ],
        "success_message": "Thank you. We'll review your information and contact you within 1 business day to schedule a consultation.",
    },
    "fitness_waiver": {
        "name": "Fitness Liability Waiver",
        "description": "Liability waiver and health screening for new gym members and trial participants.",
        "fields": [
            {"id": "full_name", "type": "text", "label": "Full Name", "required": True},
            {"id": "email", "type": "email", "label": "Email", "required": True},
            {"id": "phone", "type": "phone", "label": "Phone Number", "required": True},
            {"id": "dob", "type": "date", "label": "Date of Birth", "required": True},
            {"id": "emergency_contact", "type": "text", "label": "Emergency Contact Name & Phone", "required": True, "placeholder": "Name: (555) 123-4567"},
            {"id": "health_conditions", "type": "select", "label": "Do you have any medical conditions?", "required": True, "options": ["None", "Heart Condition", "High Blood Pressure", "Diabetes", "Asthma", "Joint Issues", "Other"]},
            {"id": "medications", "type": "textarea", "label": "Current Medications (if any)", "required": False},
            {"id": "fitness_goals", "type": "select", "label": "What are your fitness goals?", "required": False, "options": ["Weight Loss", "Muscle Building", "Endurance", "Flexibility", "General Health", "Sports Performance"]},
            {"id": "experience", "type": "select", "label": "Fitness Experience Level", "required": False, "options": ["Beginner", "Intermediate", "Advanced"]},
            {"id": "waiver", "type": "checkbox", "label": "I acknowledge that physical exercise carries inherent risks. I voluntarily assume all risks and release this facility from liability for injuries sustained during exercise.", "required": True},
        ],
        "success_message": "Thank you! Your waiver is on file. Welcome to the team — we're excited to help you reach your goals!",
    },
    "catering_inquiry": {
        "name": "Catering & Event Inquiry",
        "description": "Collect event details for catering quotes and private dining requests.",
        "fields": [
            {"id": "name", "type": "text", "label": "Your Name", "required": True},
            {"id": "email", "type": "email", "label": "Email", "required": True},
            {"id": "phone", "type": "phone", "label": "Phone", "required": True},
            {"id": "event_date", "type": "date", "label": "Event Date", "required": True},
            {"id": "guest_count", "type": "number", "label": "Number of Guests", "required": True},
            {"id": "event_type", "type": "select", "label": "Type of Event", "required": True, "options": ["Birthday Party", "Corporate Event", "Wedding", "Anniversary", "Holiday Party", "Private Dining", "Other"]},
            {"id": "budget", "type": "select", "label": "Budget Range (per person)", "required": False, "options": ["Under $25", "$25-$50", "$50-$75", "$75-$100", "Over $100"]},
            {"id": "dietary", "type": "textarea", "label": "Dietary Restrictions or Special Requests", "required": False, "placeholder": "Allergies, vegetarian, gluten-free, etc."},
        ],
        "success_message": "Thank you for your inquiry! We'll reach out within 24 hours with a custom catering proposal.",
    },
}
