"""Owner notification when the proactive scan files new suggestions.

Prod evidence (2026-07): 12 opportunity suggestions filed since June across
4 real tenants, ZERO ever accepted or declined. The scan filed cards into
``os_backlog_requests`` silently — no email, no SMS, nothing outside the
Agent OS page, which the owners weren't opening. The whole scan → accept →
draft pipeline dead-ended at "the owner never finds out".

One email per scan per tenant, only when something new was filed. The scan
itself is gated to one filing burst per tenant per day (see
``os_opportunities.run_opportunity_scan``), so this can't flood an inbox.

Best-effort by design: a notification failure never breaks the scan.

WARNING: imported near FastAPI code — do NOT add
``from __future__ import annotations`` here.
"""

import html
import logging
from typing import Any

from backend.config import settings
from backend.services.email_sender import mask_email, send_email

logger = logging.getLogger(__name__)


async def notify_new_suggestions(
    db: Any, client_id: str, suggestions: list[dict[str, Any]]
) -> bool:
    """Email the owner the suggestions just filed. Returns True if sent."""
    if not suggestions:
        return False
    try:
        rows = (
            db.table("tenants")
            .select("owner_email, owner_name")
            .eq("id", client_id)
            .limit(1)
            .execute()
        ).data or []
        owner_email = rows[0].get("owner_email") if rows else None
        if not owner_email:
            return False

        count = len(suggestions)
        safe_owner = html.escape((rows[0].get("owner_name") or "there"))
        # Summaries are generated by our own scanner, but escape anyway —
        # they embed lead counts and invoice totals derived from tenant data.
        listed = "".join(
            f"<li>{html.escape(s.get('summary') or '')}</li>" for s in suggestions
        )
        noun = "opportunity" if count == 1 else "opportunities"
        await send_email(
            to=owner_email,
            subject=f"Your AI staff spotted {count} {noun} for you",
            body_html=(
                f"<p>Hi {safe_owner},</p>"
                f"<p>While reviewing your business data, your AI staff found "
                f"{count} thing{'s' if count != 1 else ''} worth acting on:</p>"
                f"<ul>{listed}</ul>"
                "<p>Accept a suggestion and your staff drafts the messages "
                "for you — nothing is sent to a customer until you approve "
                "each one.</p>"
                f'<p><a href="{settings.frontend_url}/dashboard/agent-os" '
                'style="background:#3b82f6;color:#fff;padding:10px 20px;'
                'border-radius:6px;text-decoration:none;font-weight:600;">'
                "Review suggestions &rarr;</a></p>"
            ),
            tenant_id=client_id,
        )
        logger.info(
            "os_opportunity_notify: emailed %s for tenant %s (suggestions=%d)",
            mask_email(owner_email),
            client_id,
            count,
        )
        return True
    except Exception:
        logger.warning(
            "os_opportunity_notify: failed for tenant %s — scan unaffected",
            client_id,
            exc_info=True,
        )
        return False
