-- Migration 100: AI-drafted documents (quotes / invoices / proposals)
-- Date: 2026-04-09
-- Purpose: Extend the existing `documents` table (migration 061) to
--   store real binary files generated by the Claude Managed Agents
--   `document_drafter` agent via the docx/xlsx/pdf skills.
--
--   The agent writes the file to `/mnt/session/outputs/` inside its
--   sandbox container; the backend downloads the bytes via the
--   Anthropic Files API (beta: files-api-2025-04-14) and persists them
--   inline as bytea. We avoid Supabase storage buckets for V1 because
--   drafted quotes are small (<1 MB typical) and inline bytea keeps the
--   RLS / tenant-isolation story simple.
--
-- New columns on `documents`:
--   kind                — 'quote' | 'invoice' | 'proposal' (existing
--                         title column is human-readable)
--   file_bytes          — raw DOCX / XLSX / PDF bytes
--   file_type           — MIME-ish string ('docx', 'xlsx', 'pdf')
--   file_name           — suggested download filename
--   anthropic_file_id   — file_id returned by the Files API (for
--                         debugging / re-download; bytes are the source
--                         of truth once copied)
--   draft_metadata      — jsonb: line items, totals, agent session_id,
--                         agent version, etc.
--   generated_by_agent  — agent slug (e.g. 'document_drafter') — nullable
--                         so legacy HTML-template-based documents keep
--                         working.

ALTER TABLE documents ADD COLUMN IF NOT EXISTS kind TEXT
  CHECK (kind IS NULL OR kind IN ('quote', 'invoice', 'proposal'));

ALTER TABLE documents ADD COLUMN IF NOT EXISTS file_bytes BYTEA;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS file_type TEXT
  CHECK (file_type IS NULL OR file_type IN ('docx', 'xlsx', 'pdf'));
ALTER TABLE documents ADD COLUMN IF NOT EXISTS file_name TEXT;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS anthropic_file_id TEXT;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS draft_metadata JSONB;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS generated_by_agent TEXT;

-- The legacy HTML template pipeline requires `template_html`. New
-- AI-drafted documents don't use template_html at all — relax the
-- NOT NULL constraint so both flows can coexist.
ALTER TABLE documents ALTER COLUMN template_html DROP NOT NULL;

CREATE INDEX IF NOT EXISTS idx_documents_kind
  ON documents(kind)
  WHERE kind IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_documents_generated_by_agent
  ON documents(generated_by_agent)
  WHERE generated_by_agent IS NOT NULL;
