#!/usr/bin/env python3
"""Generate a read-only Action tool manifest from agent-service tool sources.

Does **not** import the Action Executor or tool execute functions. Parses the
``defineTool({...})`` metadata in ``agent-service/src/agent-os/actions/tools/*.ts``
plus constant aliases from ``flags.ts``.

Usage:
  python scripts/generate_action_manifest.py            # write manifest
  python scripts/generate_action_manifest.py --check    # exit 1 on drift
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOOLS_DIR = ROOT / "agent-service" / "src" / "agent-os" / "actions" / "tools"
FLAGS_PATH = ROOT / "agent-service" / "src" / "agent-os" / "actions" / "flags.ts"
MANIFEST_PATH = ROOT / "agent-service" / "src" / "agent-os" / "actions" / "action_manifest.json"

RISK_ALIASES = {
    "RISK_READ_ONLY": 0,
    "RISK_INTERNAL_MUTATION": 1,
    "RISK_EXTERNAL_COMMUNICATION": 2,
    "RISK_HIGH_IMPACT": 3,
}


def _load_flag_aliases() -> dict[str, str]:
    text = FLAGS_PATH.read_text(encoding="utf-8")
    aliases: dict[str, str] = {}
    for name, value in re.findall(
        r'export const ([A-Z0-9_]+)\s*=\s*"([^"]+)"', text
    ):
        aliases[name] = value
    return aliases


def _extract_define_tool_block(text: str) -> str | None:
    match = re.search(r"defineTool\(\s*\{", text)
    if not match:
        return None
    start = match.end() - 1
    depth = 0
    for i, ch in enumerate(text[start:], start=start):
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return text[start : i + 1]
    return None


def _field(block: str, name: str) -> str | None:
    m = re.search(rf"\b{name}\s*:\s*([^,\n]+)", block)
    if not m:
        return None
    return m.group(1).strip()


def parse_tool_file(path: Path, aliases: dict[str, str]) -> dict | None:
    text = path.read_text(encoding="utf-8")
    block = _extract_define_tool_block(text)
    if not block:
        return None

    raw_id = _field(block, "id")
    if not raw_id:
        return None
    tool_id = raw_id.strip().strip('"')
    if tool_id in aliases:
        tool_id = aliases[tool_id]

    raw_dept = _field(block, "department")
    department: str | None = None
    if raw_dept is not None:
        token = raw_dept.strip().strip('"')
        department = aliases.get(token, token if raw_dept.startswith('"') else aliases.get(token))

    raw_risk = _field(block, "riskLevel")
    if raw_risk is None:
        raise ValueError(f"{path.name}: missing riskLevel")
    risk_token = raw_risk.strip()
    if risk_token not in RISK_ALIASES:
        raise ValueError(f"{path.name}: unknown riskLevel {risk_token}")
    risk_level = RISK_ALIASES[risk_token]

    raw_approval = _field(block, "requiresApproval")
    if raw_approval is None:
        raise ValueError(f"{path.name}: missing requiresApproval")
    requires_approval = raw_approval.strip() == "true"

    raw_mutating = _field(block, "mutating")
    mutating = raw_mutating.strip() == "true" if raw_mutating else False

    # verifiable iff the tool object declares a verify hook.
    verifiable = bool(re.search(r"\basync\s+verify\s*\(|\bverify\s*:\s*", block))

    return {
        "id": tool_id,
        "department": department,
        "risk_level": risk_level,
        "requires_approval": requires_approval,
        "mutating": mutating,
        "verifiable": verifiable,
    }


def build_manifest() -> dict:
    aliases = _load_flag_aliases()
    tools: dict[str, dict] = {}
    for path in sorted(TOOLS_DIR.glob("*.ts")):
        if path.name.endswith(".test.ts"):
            continue
        parsed = parse_tool_file(path, aliases)
        if parsed is None:
            continue
        if parsed["id"] in tools:
            raise ValueError(f"duplicate tool id {parsed['id']}")
        tools[parsed["id"]] = parsed
    return {
        "_comment": (
            "Auto-generated by scripts/generate_action_manifest.py from "
            "agent-service action tool sources. Do not edit by hand — "
            "re-run the generator. Used for M9 planner catalog parity."
        ),
        "tools": tools,
    }


def write_manifest(manifest: dict) -> None:
    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST_PATH.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def check_manifest(manifest: dict) -> int:
    if not MANIFEST_PATH.exists():
        print(f"MISSING: {MANIFEST_PATH.relative_to(ROOT)}")
        return 1
    current = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    # Compare tool payloads only (ignore comment churn).
    if current.get("tools") != manifest.get("tools"):
        print("DRIFT: action_manifest.json does not match tool sources.")
        print("Run: python scripts/generate_action_manifest.py")
        old = set((current.get("tools") or {}).keys())
        new = set((manifest.get("tools") or {}).keys())
        if old != new:
            print(f"  id only in manifest: {sorted(old - new)}")
            print(f"  id only in sources:  {sorted(new - old)}")
        for tid in sorted(old & new):
            if current["tools"][tid] != manifest["tools"][tid]:
                print(f"  changed: {tid}")
                print(f"    manifest: {current['tools'][tid]}")
                print(f"    source:   {manifest['tools'][tid]}")
        return 1
    print(f"OK: action_manifest.json matches {len(manifest['tools'])} tools.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if committed manifest drifts from tool sources",
    )
    args = parser.parse_args()
    manifest = build_manifest()
    if args.check:
        return check_manifest(manifest)
    write_manifest(manifest)
    print(f"Wrote {MANIFEST_PATH.relative_to(ROOT)} ({len(manifest['tools'])} tools)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
