"""Provision AgentNexLiFy's Claude Managed Agents from config/managed_agents.yaml.

Idempotent setup script — safe to re-run. It will:

  1. Find or create the shared environment named in the YAML.
  2. For each agent in the YAML:
       - If an env var from .env.managed_agents already points at a live
         agent, update it in place (creating a new version).
       - Otherwise, look up by name via list_agents(), or create a fresh
         agent.
  3. Write the resulting IDs to .env.managed_agents.
  4. Print a summary.

Usage:

    python -m scripts.managed_agents.provision                # provision all
    python -m scripts.managed_agents.provision lead_qualifier # one agent only
    python -m scripts.managed_agents.provision --dry-run      # print plan
    python -m scripts.managed_agents.provision --recreate lead_qualifier
        # archive the existing agent and create a fresh one from scratch

Load order for existing IDs:
    .env.managed_agents > process env vars

After provisioning, load .env.managed_agents alongside your main .env so
the backend picks up the new LEAD_QUALIFIER_AGENT_ID etc. See
docs/managed-agents.md for wiring details.
"""

import argparse
import json
import logging
import os
import sys
from pathlib import Path
from typing import Any

import yaml

# Allow running as a script (python scripts/managed_agents/provision.py)
# as well as `python -m scripts.managed_agents.provision`.
_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from backend.services.managed_agents import (  # noqa: E402
    ManagedAgentsClient,
    ManagedAgentsError,
)

logger = logging.getLogger("managed_agents.provision")

CONFIG_PATH = _REPO_ROOT / "config" / "managed_agents.yaml"
ENV_OUTPUT_PATH = _REPO_ROOT / ".env.managed_agents"
ENV_VAR_ENVIRONMENT_ID = "MANAGED_AGENTS_ENVIRONMENT_ID"


def _load_config() -> dict[str, Any]:
    if not CONFIG_PATH.exists():
        raise SystemExit(f"config file not found: {CONFIG_PATH}")
    with CONFIG_PATH.open() as fh:
        cfg = yaml.safe_load(fh) or {}
    if not isinstance(cfg, dict):
        raise SystemExit(f"{CONFIG_PATH}: expected a YAML mapping at the top level")
    return cfg


def _load_existing_env() -> dict[str, str]:
    """Load previously-persisted IDs from .env.managed_agents (if any).

    Process environment variables override file values so that operators
    can set a one-shot ID without editing the file.
    """
    result: dict[str, str] = {}
    if ENV_OUTPUT_PATH.exists():
        for raw in ENV_OUTPUT_PATH.read_text().splitlines():
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            key, _, value = line.partition("=")
            result[key.strip()] = value.strip()
    for key in list(result.keys()) + [ENV_VAR_ENVIRONMENT_ID]:
        env_val = os.environ.get(key)
        if env_val:
            result[key] = env_val
    # Catch any env-var only names we haven't seen yet.
    for env_name, env_val in os.environ.items():
        if env_name.endswith("_AGENT_ID") and env_val:
            result[env_name] = env_val
    return result


def _write_env_file(values: dict[str, str]) -> None:
    lines = [
        "# Auto-generated by scripts/managed_agents/provision.py — do not edit by hand.",
        "# Load this alongside your main .env so the backend can read the agent IDs.",
        "",
    ]
    for key in sorted(values):
        lines.append(f"{key}={values[key]}")
    ENV_OUTPUT_PATH.write_text("\n".join(lines) + "\n")
    logger.info("wrote %d entries to %s", len(values), ENV_OUTPUT_PATH)


def _ensure_environment(
    client: ManagedAgentsClient,
    cfg: dict[str, Any],
    existing: dict[str, str],
    *,
    dry_run: bool,
) -> str:
    env_cfg = cfg.get("environment") or {}
    name = env_cfg.get("name")
    if not name:
        raise SystemExit("config: environment.name is required")

    existing_id = existing.get(ENV_VAR_ENVIRONMENT_ID)
    if existing_id:
        try:
            env_obj = client.get_environment(existing_id)
            logger.info("environment already exists: %s (%s)", existing_id, env_obj.get("name"))
            return existing_id
        except ManagedAgentsError as exc:
            logger.warning(
                "configured environment %s is stale (%s) — will recreate",
                existing_id, exc,
            )

    # Look up by name in case a previous run created one but we lost the ID.
    try:
        listing = client.list_environments()
    except ManagedAgentsError as exc:
        logger.warning("list_environments failed: %s", exc)
        listing = {}
    for env_obj in (listing.get("data") or []):
        if env_obj.get("name") == name:
            env_id = env_obj.get("id")
            if isinstance(env_id, str):
                logger.info("found existing environment by name: %s", env_id)
                return env_id

    networking = env_cfg.get("networking", "unrestricted")
    description = env_cfg.get("description")
    if dry_run:
        logger.info("[dry-run] would create environment name=%s networking=%s", name, networking)
        return "env_DRY_RUN"

    created = client.create_environment(
        name=name,
        networking=networking,
        description=description,
    )
    env_id = created.get("id")
    if not isinstance(env_id, str):
        raise SystemExit(f"create_environment returned unexpected payload: {created!r}")
    logger.info("created environment: %s (name=%s)", env_id, name)
    return env_id


def _build_agent_body(agent_cfg: dict[str, Any]) -> dict[str, Any]:
    body: dict[str, Any] = {
        "name": agent_cfg["name"],
        "model": agent_cfg["model"],
    }
    for field in ("system", "description"):
        if agent_cfg.get(field):
            body[field] = agent_cfg[field]
    for field in ("tools", "mcp_servers", "skills"):
        if agent_cfg.get(field):
            body[field] = agent_cfg[field]
    if agent_cfg.get("metadata"):
        body["metadata"] = agent_cfg["metadata"]
    return body


def _find_agent_by_name(client: ManagedAgentsClient, name: str) -> str | None:
    try:
        listing = client.list_agents()
    except ManagedAgentsError as exc:
        logger.warning("list_agents failed: %s", exc)
        return None
    for agent_obj in (listing.get("data") or []):
        if agent_obj.get("name") == name:
            agent_id = agent_obj.get("id")
            if isinstance(agent_id, str):
                return agent_id
    return None


def _ensure_agent(
    client: ManagedAgentsClient,
    slug: str,
    agent_cfg: dict[str, Any],
    existing: dict[str, str],
    *,
    dry_run: bool,
    recreate: bool,
) -> tuple[str, str, int | None]:
    """Returns (env_var_name, agent_id, version)."""
    env_var = agent_cfg.get("env_var") or f"{slug.upper()}_AGENT_ID"
    name = agent_cfg.get("name") or slug
    existing_id = existing.get(env_var)
    body = _build_agent_body(agent_cfg)

    if recreate and existing_id:
        logger.info("--recreate: archiving %s before creating a fresh agent", existing_id)
        if not dry_run:
            try:
                client.archive_agent(existing_id)
            except ManagedAgentsError as exc:
                logger.warning("archive of %s failed (continuing): %s", existing_id, exc)
        existing_id = None

    # If we think we have an ID, verify it still exists.
    if existing_id:
        try:
            client.get_agent(existing_id)
        except ManagedAgentsError as exc:
            logger.warning("configured agent %s is stale (%s) — clearing", existing_id, exc)
            existing_id = None

    # Fall back to name-based lookup.
    if not existing_id:
        existing_id = _find_agent_by_name(client, name)
        if existing_id:
            logger.info("found existing agent %s by name: %s", slug, existing_id)

    if existing_id:
        if dry_run:
            logger.info("[dry-run] would update agent %s (%s)", slug, existing_id)
            return env_var, existing_id, None
        updated = client.update_agent(existing_id, **body)
        version = updated.get("version")
        logger.info(
            "updated agent %s → %s (version=%s)", slug, existing_id, version,
        )
        return env_var, existing_id, version

    if dry_run:
        logger.info("[dry-run] would create agent %s name=%s", slug, name)
        return env_var, "agent_DRY_RUN", None
    created = client.create_agent(**body)
    agent_id = created.get("id")
    if not isinstance(agent_id, str):
        raise SystemExit(f"create_agent returned unexpected payload: {created!r}")
    version = created.get("version")
    logger.info("created agent %s → %s (version=%s)", slug, agent_id, version)
    return env_var, agent_id, version


def main() -> int:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
    )

    parser = argparse.ArgumentParser(description=__doc__ or "")
    parser.add_argument(
        "agents",
        nargs="*",
        help="Optional list of agent slugs to provision (default: all).",
    )
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument(
        "--recreate",
        action="store_true",
        help="Archive the existing agents and create fresh ones.",
    )
    parser.add_argument(
        "--print-body",
        action="store_true",
        help="Print the exact CreateAgent body that will be sent (debugging).",
    )
    args = parser.parse_args()

    cfg = _load_config()
    agents_cfg = cfg.get("agents") or {}
    if not agents_cfg:
        raise SystemExit(f"{CONFIG_PATH}: no agents defined")

    selected = args.agents or list(agents_cfg.keys())
    unknown = [name for name in selected if name not in agents_cfg]
    if unknown:
        raise SystemExit(f"unknown agent(s): {', '.join(unknown)}")

    if args.print_body:
        for slug in selected:
            body = _build_agent_body(agents_cfg[slug])
            print(f"=== {slug} ===")
            print(json.dumps(body, indent=2))
        return 0

    client = ManagedAgentsClient()

    existing = _load_existing_env()
    env_id = _ensure_environment(client, cfg, existing, dry_run=args.dry_run)

    result: dict[str, str] = {ENV_VAR_ENVIRONMENT_ID: env_id}

    for slug in selected:
        env_var, agent_id, _version = _ensure_agent(
            client,
            slug,
            agents_cfg[slug],
            existing,
            dry_run=args.dry_run,
            recreate=args.recreate,
        )
        result[env_var] = agent_id

    # Preserve any existing env values we didn't touch this run (e.g. other
    # agents that weren't selected).
    for key, value in existing.items():
        result.setdefault(key, value)

    if not args.dry_run:
        _write_env_file(result)

    print()
    print("Managed Agents provisioning complete.")
    print()
    print(f"  {ENV_VAR_ENVIRONMENT_ID}={result[ENV_VAR_ENVIRONMENT_ID]}")
    for slug in selected:
        env_var = (
            agents_cfg[slug].get("env_var") or f"{slug.upper()}_AGENT_ID"
        )
        print(f"  {env_var}={result.get(env_var, '(unchanged)')}")
    print()
    if not args.dry_run:
        print(f"Wrote IDs to {ENV_OUTPUT_PATH.relative_to(_REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
